name: Haskell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: timbod7/setup-stack@master
    - name: Cache multiple paths
      uses: actions/cache@v2
      with:
       path: |
        ~/.stack
       key: ${{ runner.os }}-${{ hashFiles('dfinity-discovery.cabal') }}

    - name: build
      run: |
        rm -r ~/.stack/setup-exe*
        stack init
        stack build
        
    - name: test
      run: stack test
    - name: example
      run: |
        scripts/discovery-test.sh 0
        scripts/discovery-test.sh 1
        scripts/discovery-test.sh 2
